CREATE TABLE AIRPLANE
( 
	ID                   varchar(40)  NOT NULL ,
	CAPACITY             integer  NULL ,
	TYPE                 varchar(40)  NULL ,
	COMPANY              varchar(40)  NULL ,
	CODE                 varchar(30)  NULL 
)
go



ALTER TABLE AIRPLANE
	ADD CONSTRAINT XPKAIRPLANE PRIMARY KEY  CLUSTERED (ID ASC)
go



CREATE TABLE AIRPORT
( 
	CODE                 varchar(30)  NOT NULL ,
	NAME                 varchar(50)  NULL ,
	CITY                 VARCHAR(15)  NULL ,
	ADDRESS              varchar(50)  NULL ,
	COUNTRY              varchar(10)  NULL ,
	TERMINALS            integer  NULL ,
	CAPACITY             integer  NULL 
)
go



ALTER TABLE AIRPORT
	ADD CONSTRAINT XPKAIRPORT PRIMARY KEY  CLUSTERED (CODE ASC)
go



CREATE TABLE CORPORATION
( 
	REG_NUM              integer  NOT NULL ,
	NAME                 varchar(50)  NULL ,
	ADDRESS              varchar(50)  NULL ,
	PHONE                integer  NULL 
)
go



ALTER TABLE CORPORATION
	ADD CONSTRAINT XPKCORPORATION PRIMARY KEY  CLUSTERED (REG_NUM ASC)
go




CREATE TABLE FLIES
( 
	CNIC                 integer  NOT NULL ,
	FLIGHT_NO            integer  NOT NULL 
)
go



ALTER TABLE FLIES
	ADD CONSTRAINT XPKFLIES PRIMARY KEY  CLUSTERED (CNIC ASC,FLIGHT_NO ASC)
go



CREATE TABLE FLIGHT
( 
	FLIGHT_NO            integer  NOT NULL ,
	"TO"                   varchar(20)  NULL ,
	"FROM"                 varchar(20)  NULL ,
	DEPARTURE_DATETIME   datetime  NULL ,
	ARRIVAL_DATETIME     datetime  NULL ,
	DISTANCE             integer  NULL ,
	ID                   varchar(40)  NULL 
)
go



ALTER TABLE FLIGHT
	ADD CONSTRAINT XPKFLIGHT PRIMARY KEY  CLUSTERED (FLIGHT_NO ASC)
go



CREATE TABLE FLIGHT_CONTROLLER
( 
	ID                   varchar(30)  NOT NULL ,
	YEARS_OF_SERVICE     integer  NULL ,
	CNIC                 integer  NOT NULL ,
	CODE                 varchar(30)  NULL 
)
go



ALTER TABLE FLIGHT_CONTROLLER
	ADD CONSTRAINT XPKFLIGHT_CONTROLLER PRIMARY KEY  CLUSTERED (CNIC ASC)
go



CREATE TABLE MAINTAINS
( 
	CNIC                 integer  NOT NULL ,
	WORKCODE             varchar(20)  NOT NULL ,
	ID                   varchar(40)  NOT NULL 
)
go



ALTER TABLE MAINTAINS
	ADD CONSTRAINT XPKMAINTAINS PRIMARY KEY  CLUSTERED (CNIC ASC,WORKCODE ASC,ID ASC)
go





CREATE TABLE OWNS
( 
	ID                   varchar(40)  NOT NULL ,
	REG_NUM              integer  NOT NULL 
)
go



ALTER TABLE OWNS
	ADD CONSTRAINT XPKOWNS PRIMARY KEY  CLUSTERED (ID ASC,REG_NUM ASC)
go



CREATE TABLE PASSENGER
( 
	CNIC                 integer  NOT NULL ,
	PASSPORT_NO          integer  NULL ,
	DESTINATION          varchar(20)  NULL 
)
go



ALTER TABLE PASSENGER
	ADD CONSTRAINT XPKPASSENGER PRIMARY KEY  CLUSTERED (CNIC ASC)
go



CREATE TABLE PERSON
( 
	CNIC                 integer  NOT NULL ,
	NAME                 varchar(30)  NULL ,
	PHONE                integer  NULL ,
	ADDRESS              varchar(30)  NULL 
)
go



ALTER TABLE PERSON
	ADD CONSTRAINT XPKPERSON PRIMARY KEY  CLUSTERED (CNIC ASC)
go



CREATE TABLE PILOT
( 
	LIC_NUM              varchar(30)  NULL ,
	PASSPORT_NO          integer  NULL ,
	YEARS_OF_SERVICE     integer  NULL ,
	CNIC                 integer  NOT NULL 
)
go



ALTER TABLE PILOT
	ADD CONSTRAINT XPKPILOT PRIMARY KEY  CLUSTERED (CNIC ASC)
go



CREATE TABLE RESERVES
( 
	CNIC                 integer  NOT NULL ,
	FLIGHT_NO            integer  NOT NULL 
)
go



ALTER TABLE RESERVES
	ADD CONSTRAINT XPKRESERVES PRIMARY KEY  CLUSTERED (CNIC ASC,FLIGHT_NO ASC)
go




CREATE TABLE SERVICE
( 
	WORKCODE             varchar(20)  NOT NULL ,
	DATE                 datetime  NULL ,
	HOURS                integer  NULL ,
	ID                   varchar(40)  NOT NULL 
)
go



ALTER TABLE SERVICE
	ADD CONSTRAINT XPKSERVICE PRIMARY KEY  CLUSTERED (WORKCODE ASC,ID ASC)
go



CREATE TABLE SERVICE_STAFF
( 
	ID                   varchar(30)  NULL ,
	TITLE                varchar(20)  NULL ,
	"SHIFT"                varchar(10)  NULL ,
	CNIC                 integer  NOT NULL 
)
go



ALTER TABLE SERVICE_STAFF
	ADD CONSTRAINT XPKSERVICE_STAFF PRIMARY KEY  CLUSTERED (CNIC ASC)
go




ALTER TABLE AIRPLANE
	ADD CONSTRAINT R_31 FOREIGN KEY (CODE) REFERENCES AIRPORT(CODE)
		ON DELETE Cascade
		ON UPDATE Cascade
go















ALTER TABLE FLIES
	ADD CONSTRAINT R_43 FOREIGN KEY (CNIC) REFERENCES PILOT(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE FLIES
	ADD CONSTRAINT R_47 FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE FLIGHT
	ADD CONSTRAINT R_32 FOREIGN KEY (ID) REFERENCES AIRPLANE(ID)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE FLIGHT_CONTROLLER
	ADD CONSTRAINT R_33 FOREIGN KEY (CNIC) REFERENCES PERSON(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE FLIGHT_CONTROLLER
	ADD CONSTRAINT R_37 FOREIGN KEY (CODE) REFERENCES AIRPORT(CODE)
		ON DELETE Cascade
		ON UPDATE Cascade
go









ALTER TABLE MAINTAINS
	ADD CONSTRAINT R_39 FOREIGN KEY (CNIC) REFERENCES SERVICE_STAFF(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE MAINTAINS
	ADD CONSTRAINT R_40 FOREIGN KEY (WORKCODE,ID) REFERENCES SERVICE(WORKCODE,ID)
		ON DELETE Cascade
		ON UPDATE Cascade
go







ALTER TABLE OWNS
	ADD CONSTRAINT R_25 FOREIGN KEY (ID) REFERENCES AIRPLANE(ID)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE OWNS
	ADD CONSTRAINT R_58 FOREIGN KEY (REG_NUM) REFERENCES CORPORATION(REG_NUM)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE PASSENGER
	ADD CONSTRAINT R_48 FOREIGN KEY (CNIC) REFERENCES PERSON(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE PILOT
	ADD CONSTRAINT R_36 FOREIGN KEY (CNIC) REFERENCES PERSON(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE RESERVES
	ADD CONSTRAINT R_49 FOREIGN KEY (CNIC) REFERENCES PASSENGER(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE RESERVES
	ADD CONSTRAINT R_50 FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO)
		ON DELETE Cascade
		ON UPDATE Cascade
go











ALTER TABLE SERVICE
	ADD CONSTRAINT R_38 FOREIGN KEY (ID) REFERENCES AIRPLANE(ID)
		ON DELETE Cascade
		ON UPDATE Cascade
go




ALTER TABLE SERVICE_STAFF
	ADD CONSTRAINT R_34 FOREIGN KEY (CNIC) REFERENCES PERSON(CNIC)
		ON DELETE Cascade
		ON UPDATE Cascade
go
